<?php

/**
 * @file
 * Provides basic web profiles for sites.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uiowa_person_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.uiowa_person':
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }

      /* @var \Drupal\Core\Extension\ModuleHandler $moduleHandler*/
      $moduleHandler = \Drupal::service('module_handler');
      if ($moduleHandler->moduleExists('markdown')) {
        $filters = $moduleHandler->invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function uiowa_person_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'uiowa_person/uiowa_person_styling';
}

/**
 * Implements hook_theme().
 */
function uiowa_person_theme(array $variables) {
  $theme = [];

  // Suggestion for the template.
  $theme['node__person'] = [
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--person',
    'path' => drupal_get_path('module', 'uiowa_person') . '/templates',
  ];

  return $theme;
}
